name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dotnet-format
      run: |
        dotnet tool restore
    - name: Format
      run: |
        dotnet format -w -s
        
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: ${{ matrix.configuration }} Build
      run: |
        dotnet build --no-restore --configuration ${{ matrix.configuration }}
    - name: ${{ matrix.configuration }} Test
      run: |
        dotnet test --no-build --configuration ${{ matrix.configuration }} --verbosity normal
