name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dotnet-format
      run: |
        dotnet tool install --global dotnet-format --version 5.1.225507
    - name: Format
      run: |
        dotnet format -w -s
        
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: Release Build
      run: |
        dotnet build --no-restore --configuration Release
    - name: Test
      run: |
        dotnet test --no-build --configuration Release --verbosity normal